### ISSUE TITLE
Question : could we have the possibility to store the BI view in user dashboard, like any other graph or cross table ?

### ISSUE THREAD

**Issue by mamaf** [onesteinbv/addons-onestein#11]

**Comment by astirpe** [comment]
This functionality is available for V8, V9 and V10: it's possible to install the module **board** (in combination with **bi_view_editor**) and the use can add the view in his Dashboard.

The BI View Editor for V9 is now available in: [https://github.com/OCA/reporting-engine/tree/9.0](https://github.com/OCA/reporting-engine/tree/9.0).

The BI View Editor for V10 is not yet merged in OCA, but is already available [here](https://github.com/onesteinbv/reporting-engine/tree/10_porting_bi_view_editor).

**Comment by astirpe** [comment]
This functionality is available in the latest version of the module for V8, V9 and V10: it's possible to install the module board (in combination with bi_view_editor) so that the user can add the view in his Dashboard.

The BI View Editor for V8 is available in: [https://github.com/onesteinbv/addons-onestein/tree/8.0](https://github.com/onesteinbv/addons-onestein/tree/8.0)

The BI View Editor for V9 is available in: [https://github.com/OCA/reporting-engine/tree/9.0](https://github.com/OCA/reporting-engine/tree/9.0)

The BI View Editor for V10 is available in: [https://github.com/onesteinbv/addons-onestein/tree/10.0](https://github.com/onesteinbv/addons-onestein/tree/10.0)
