### ISSUE TITLE
cost_center info not shown in journal entries

### ISSUE THREAD

**Issue by funcurv** [onesteinbv/addons-onestein#20]
Hi,

is this on purpose or is the cost_center info not properly populated into the journal_entries? Cost_center ifo always empty in journal entries.

Using Odoo v10 on Ubuntuu and on Windows (for demoing).

br

Werner

**Comment by astirpe** [comment]
Hi @funcurv , this issue was fixed 8 days ago for Odoo v10, could you try with the latest code?
I just tried locally and it works fine for me: the cost center is set in the journal entries.
This is just a porting of the Cost Center module already made for OdooV8, its functionality is the same.

We would like to publish this module in OCA, maybe you would be interested in reviewing this pull request:
 https://github.com/OCA/account-financial-tools/pull/359

Thank you for the feedback!

**Comment by funcurv** [comment]
Hi,

thanks. missed your update from 8 days ago. Now it works.
thanks.

Will do the review the pull request later this week.

br

Werner
