### ISSUE TITLE
[MIG] 11.0 account_cost_center

### ISSUE THREAD

**Issue by pmartineznetquest** [onesteinbv/addons-onestein#42]
Dear Onestein team, 

We have tested and evaluated v10 account_cost_center module, that works perfectly and fits our requirements. 

Now we are implementing a v11 environment and we wonder if you are planning to migrate it soon or it is not high priorized in your backlog. Maybe we can collaborate. 

Thanks a lot!
Pere

**Comment by astirpe** [comment]
@pmartineznetquest yes, we will port the module to v11 during the next weeks.
Did you already try to use this v10 module in your v11 server? Probably it will be already working fine, without any need to change any line of code.

**Comment by pmartineznetquest** [comment]
Hi, @astirpe! Thank you for the answer and for sharing the module, of course!

Yes, we have tested it on a v11 and works perfect, so we were thinking about to migrate it to the v11 specification to prevent any future incompatibility. 

Our strategy is to migrate and share (in the OCA if possible) all <11 modules needed to warranty their life and continuity or, at least, to ensure support for future migrations. 

As far as I know, it is a very useful module for a lot of scenarios and customers, and that's why we were thinking about to collaborate to migrate or to make it OCA compliant, if you are considering it. 

So don't hesitate on contacting us if you need any help.  

Thank you again!

**Comment by astirpe** [comment]
@pmartineznetquest thank you for the interest!

- The version 8.0 of his module in already merged in OCA (see https://github.com/OCA/account-financial-tools/tree/8.0).
- The version 9.0 was proposed to be merged to OCA (see: https://github.com/OCA/account-financial-tools/pull/442) but the pull request is still pending. May you want to speed-up the approval process and write a positive review in that pull request?
- The version 10.0 is not yet proposed to OCA since I was waiting the approval for v9.0. Feel free to open a PR in OCA if you want, otherwise I will do it during the next days.
- Regarding the version 11.0, I just added the module in our repository (https://github.com/onesteinbv/addons-onestein/tree/11.0) since you said it works fine ;) I will open a PR to OCA as well.

**Comment by levkar** [comment]
Hello, here are few things I noticed on V11 port:
- account_analytic_id  already exists in account.invoice.report model. 
- account_analytic_id  already exists in view_account_invoice_report_search view.
- report files can be moved to report folder.

**Comment by astirpe** [comment]
@levkar Thank you very much! I just removed the duplicated `account_analytic_id` occurrence from that module.

**Comment by levkar** [comment]
Thank you very much!

**Comment by pmartineznetquest** [comment]
Thank you all! Good job!
