### ISSUE TITLE
bi_view_editor: Request : Add to dashboard link

### ISSUE THREAD

**Issue by Moret84** [onesteinbv/addons-onestein#8]
Is it possible to add to the module a link to add a BI view to the dashboard as we can found in for example Sale order graph view ?

**Comment by astirpe** [comment]
This functionality is available in the latest version of the module for V8, V9 and V10: it's possible to install the module board (in combination with bi_view_editor) so that the user can add the view in his Dashboard.

The BI View Editor for V8 is available in: [https://github.com/onesteinbv/addons-onestein/tree/8.0](https://github.com/onesteinbv/addons-onestein/tree/8.0)

The BI View Editor for V9 is available in: [https://github.com/OCA/reporting-engine/tree/9.0](https://github.com/OCA/reporting-engine/tree/9.0)

The BI View Editor for V10 is available in: [https://github.com/onesteinbv/addons-onestein/tree/10.0](https://github.com/onesteinbv/addons-onestein/tree/10.0)
